version: 1
kind: pipeline
spec:
  stages:
    - name: build
      type: ci
      spec:
        steps:
          - name: check-node-version
            type: run
            spec:
              container: node
              script: node -v & yarn -v
          - name: install
            type: run
            spec:
              container: node
              script: yarn install
          - name: build
            type: run
            spec:
              container: node
              script: yarn build
