name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.email "aser1989@sina.com"
          git config --global user.name "CI Bot"
      
      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/ASER1989/aser1989.cn.git
      
      - name: Update deployment.yaml
        run: |
          sed -i "s|image: registry.cn-hangzhou.aliyuncs.com/aser/aser1989.cn:.*|image: registry.cn-hangzhou.aliyuncs.com/aser/aser1989.cn:${{ github.sha }}|" .argocd/deployment.yaml
          git commit -am "Update deployment image to ${{ github.sha }}"
          git push

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Project
        run: yarn build

      - name: Get Version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Package Version: $VERSION"

      - name: Log in to Aliyun Docker Registry
        run: |
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login registry.cn-hangzhou.aliyuncs.com -u "${{ secrets.ALIYUN_DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t registry.cn-hangzhou.aliyuncs.com/aser/aser1989.cn:${{ env.VERSION }} .
          docker tag registry.cn-hangzhou.aliyuncs.com/aser/aser1989.cn:${{ env.VERSION }} registry.cn-hangzhou.aliyuncs.com/aser/aser1989.cn:latest

      - name: Push Docker Image
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/aser/aser1989.cn:${{ env.VERSION }}
          docker push registry.cn-hangzhou.aliyuncs.com/aser/aser1989.cn:latest
          
       
